apiVersion: v1
kind: Service
metadata:
  name: {{ include "chirpstack.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.chirpstack.service.type }}
  ports:
    - port: {{ .Values.chirpstack.service.port }}
      targetPort: {{ .Values.chirpstack.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "chirpstack.selectorLabels" . | nindent 4 }}
