{{- if .Values.chirpstack.enabled.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.chirpstack.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.chirpstack.secret.values }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
