apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatewaybridge.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gatewaybridge.service.type }}
  ports:
    - port: {{ .Values.gatewaybridge.service.port }}
      targetPort: {{ .Values.gatewaybridge.service.targetPort }}
      protocol: UDP
      name: http
  selector:
    {{- include "gatewaybridge.selectorLabels" . | nindent 4 }}
