apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatewaybridgebasicstation.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gatewaybridgebasicstation.service.type }}
  ports:
    - port: {{ .Values.gatewaybridgebasicstation.service.port }}
      targetPort: {{ .Values.gatewaybridgebasicstation.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "gatewaybridgebasicstation.selectorLabels" . | nindent 4 }}
