{{- if .Values.gatewaybridge.enabled.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chirpstack.fullname" . }}-gateway-bridge-toml-config
  namespace: {{ .Values.namespace }}
data:
{{- range $path, $_ := $.Files.Glob "configuration/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
