{{- if .Values.certificates }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chirpstack.fullname" . }}-certs
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  tls.crt: {{ .Values.certificates.cert | quote }}
  tls.key: {{ .Values.certificates.key | quote }}
  ca.crt: {{ .Values.certificates.ca | quote }}
{{- end }}
