apiVersion: v1
kind: Secret
metadata:
  name: vernemq-certs
  namespace: vernemq # Change this if your namespace is different
  labels:
    app.kubernetes.io/name: vernemq
    app.kubernetes.io/managed-by: manual
type: kubernetes.io/tls
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFrTCCA5WgAwIBAgIURg6LngaUHvsgH5Nr6FDQNctVOMQwDQYJKoZIhvcNAQEL
    BQAwZjELMAkGA1UEBhMCU0cxEjAQBgNVBAgMCVNpbmdhcG9yZTESMBAGA1UEBwwJ
    U2luZ2Fwb3JlMQ4wDAYDVQQKDAVNeU9yZzEMMAoGA1UECwwDUEtJMREwDwYDVQQD
    DAhNeVJvb3RDQTAeFw0yNjA0MjkwNjQ1NTdaFw0zNjA0MjYwNjQ1NTdaMGYxCzAJ
    BgNVBAYTAlNHMRIwEAYDVQQIDAlTaW5nYXBvcmUxEjAQBgNVBAcMCVNpbmdhcG9y
    ZTEOMAwGA1UECgwFTXlPcmcxDDAKBgNVBAsMA1BLSTERMA8GA1UEAwwITXlSb290
    Q0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCMnnYC9VO8GtSnEl5N
    R5gu/iBz2Je1R1SJns21U8gJGWZnzgWBP6N6CPV7Bsq3uTaIp9pUZB1vxkh32v7+
    TMfjZPjMZ0ZNpnNVxRTuHc1ZeyGQdK8F84AcWGpWQfhIeQ+6kmn1Az37HY/LJqgr
    FmcCGgwc3YkkWkcQg+lMPpq7Q8RGOo/A1qOtesi/Y8GYYjfvcM+0qCUODBgs9M38
    KIm96tnfdb/2iwe7eGLDmW6q4CZISDh6gu2b98PUjTADWZKZxmiDeaFZGdMxW9+p
    GVMNCnNS5GyfN9MJx6Ybf7zIK+5WaeHusyFE8JyCgHgauBUyv9Y6+nXUPlZ357po
    DAu3Udc2Qe2lsGCnUFjTZMkHYhvC5JQ2Lkmliz2gh00yBUor/R+rWyX9pGklWr9j
    2ccgGKPxcPvkz6HgO/9bbJGj/iPLQZlloMmewAIzDMCAnturLY2kbA3e2/5bogn5
    x5gNhq7kMuhGhS+2Dv7jCHrYcF1T8xMASOOtW3g/g/7iFaI9rac5bn5u08otwyYi
    CDk0C9b47GqY8i+AN4EbYnUlXF1zukALl+hEjZ0BY1C8y92Yf/WEwRNrJfI8I8+3
    8ceOviWzRz7oy8vdfbUFWVLy76MFu1ibCc6LUDX1vexB2PGJd0DmadakVKks0WHF
    8iGq7C1y8YIlaN4UMqeUStoTWwIDAQABo1MwUTAdBgNVHQ4EFgQUiyWjePh3zrD6
    Q7MW3pbeUu6fjqIwHwYDVR0jBBgwFoAUiyWjePh3zrD6Q7MW3pbeUu6fjqIwDwYD
    VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAcvPXZNZ+CZcXjAMm4GvV
    TIU05LYA0Jg4vYYcnU5/jLd4a8bXIhmsd+fU2y3+hBj6AN6p5gM7xyq9DQPJpX7P
    e/+bthiW8kYUW7O74fJM9rC/Bg+Ks+NdltLey9HujmYrRyXGsgKx91udzBSGJZzx
    1oTUxlDXUio0fMcHK42zKSrqMlU8C8tNUWuO3ke9hCLLIl2pLWB5MDTea6sj0fCb
    Q35rKzYCHpM+4hNsouwLaCd4Z0Yx6N4CgPk8bi59TNDZfpEu9DijJeCpid05qsGI
    QIi2v27YuH20/HuTc75qBywimqO3Rol69/+MGXHdkEzwKKQPHdJHAzIsWGsnLVWB
    9HgFEUmMnIPbCFpjH3GYrfY6VUVX7AErSUpBZ17eyTHFkROUsyg8Ci4bA10yE491
    pEm4J38illRK8WFUxiwIuoSJjoL18R2hZS+gQsl1vAeqglrhzJ8gC7jFK08mkiyX
    Q1jLCJuxYIvU8Ga/JoRUjqqHNoCG3983WElKIWTqAVHswLTxCGFg9JXzIwN5fVs6
    N2QK1QU3UFLj5PymlpeLvvnnzqNnBSBESojW6PoJ/O+3JHS4BP0MKPKoJJH85t9I
    x41RpJghY8WcftEG0/qUDHvUcBsQLBfR6NjroLBZY+5NJyGJvxB5ZWBgBVI4mUif
    RAA0zBxT60qclkCqSIfFW6o=
    -----END CERTIFICATE-----
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFNTCCAx2gAwIBAgIUU1sJ0Mc6G279W0sqKC24NaHXvQ0wDQYJKoZIhvcNAQEL
    BQAwZjELMAkGA1UEBhMCU0cxEjAQBgNVBAgMCVNpbmdhcG9yZTESMBAGA1UEBwwJ
    U2luZ2Fwb3JlMQ4wDAYDVQQKDAVNeU9yZzEMMAoGA1UECwwDUEtJMREwDwYDVQQD
    DAhNeVJvb3RDQTAeFw0yNjA0MzAxMTQyMThaFw0yODA4MDIxMTQyMThaMGkxCzAJ
    BgNVBAYTAlNHMRIwEAYDVQQIDAlTaW5nYXBvcmUxEjAQBgNVBAcMCVNpbmdhcG9y
    ZTEOMAwGA1UECgwFTXlPcmcxCzAJBgNVBAsMAklUMRUwEwYDVQQDDAw1Ny4xNTEu
    NzkuMTgwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCXtWDTrC/YY1eq
    xeHCTCKOv+S4DgH73Sh5541yz5zkcys7XA3LpcNQ/OvtnIeK6u9SSMr+pWQXr2Ob
    FnA/bdtIhK/R3cm7qryHNciM+bpaXBIc1L8T+GH6k9vrqTv16Ara9cxbz5haZwrW
    ozltBnLo7y6amB/8kD03NAveDlel2NIaLRZVGA4IdfdSoyn86xoPj2LOPw98dpRZ
    qaCxSPX1JO7Mt9/iqXdvUwbZvkHe+zbaL3de8hcj3gAG/m7tuZwasK2fJiyXfO/r
    E+G0RMy7wfA25wyqtIYyUtL5RMvAqNwDqJmIpPaRuzNED51YqkWPF1C2ZY/8ogr2
    gcNyERGFAgMBAAGjgdcwgdQwbQYDVR0RBGYwZIIPdmVybmVtcS52ZXJuZW1xgg12
    ZXJuZW1xLmxvY2FsghN2ZXJuZW1xLnZlcm5lbXEuc3ZjgiF2ZXJuZW1xLnZlcm5l
    bXEuc3ZjLmNsdXN0ZXIubG9jYWyHBH8AAAGHBDmXTxIwDgYDVR0PAQH/BAQDAgWg
    MBMGA1UdJQQMMAoGCCsGAQUFBwMBMB0GA1UdDgQWBBS+Z1LzBPvVI4MYmogTQCQW
    UpwIiDAfBgNVHSMEGDAWgBSLJaN4+HfOsPpDsxbelt5S7p+OojANBgkqhkiG9w0B
    AQsFAAOCAgEAKpB5wqw/bmKPBv8LsUNAwyivdXivFHTg1k/cV209EkpFR0nBprwj
    g+VzYezTvedkclDWfKQNrGLpie41evyPwADG1Ey/x/Xl2k62jevnshprAsCX8khX
    +FwcbM292+jY1VazQK8AOG/ieI2j6wVQo5fG9oWmVnl/otBcF6+zTWAOPbTUgkIZ
    4tZ7NIgpcnQcAIbCpkIUwMj+nY5sM2JcKw508g4QDF+bzacseRDLOci9j49B7HOg
    CGw4A7uEKYRPvhtLjlcg6nFVyo3iAyD7Z6XF6+Xge9A0ebwnpF9fNBWpoTPMWPVA
    QrPhHXLyy6uriGfT45X359ZWGlkpqnGlNAZZE50N6R6oCOwKJryVMy0k+ygWDSay
    QJucgzCUXCYa6Ioj1WVnJIGmcWwg641npu65vP/YotoHT0FSYqQOQqVqeRg0bFPu
    /C1g7i5kWpz8247EmZGRNB7UmtAKFv5BLx5EAYgLMe5c2h0vHeGhjYyT2JvmmpCk
    5HwnrRpSVMBJcHQWu8eFsbVnIPjnJpL/smGScHf9g12kEvIofNbhEFPFhmV089Cc
    FOfPfRuPiDFTv3mCmWhzHflW1uNoiDm6ZszWpTXlNy+xiWo3VJPvn9YnIIMBBPyT
    RaMVCjOAO08MmqT4dtiRqtLLgNzLz3JH9lM2ER0WVVBXsX87ITC+rfg=
    -----END CERTIFICATE-----

  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCXtWDTrC/YY1eq
    xeHCTCKOv+S4DgH73Sh5541yz5zkcys7XA3LpcNQ/OvtnIeK6u9SSMr+pWQXr2Ob
    FnA/bdtIhK/R3cm7qryHNciM+bpaXBIc1L8T+GH6k9vrqTv16Ara9cxbz5haZwrW
    ozltBnLo7y6amB/8kD03NAveDlel2NIaLRZVGA4IdfdSoyn86xoPj2LOPw98dpRZ
    qaCxSPX1JO7Mt9/iqXdvUwbZvkHe+zbaL3de8hcj3gAG/m7tuZwasK2fJiyXfO/r
    E+G0RMy7wfA25wyqtIYyUtL5RMvAqNwDqJmIpPaRuzNED51YqkWPF1C2ZY/8ogr2
    gcNyERGFAgMBAAECggEABdTD5v7sS93tpbO7bLNudJwtl2F6dArZHm5nAm22cxV2
    KO7t3ND/Q+Kk0to8X3uOPVRs8QK8aSilpHVlVRrM3emztFZZBayXWH8ZuUlz/zsg
    uxj2Szc11OLQBivYESidGjNuamz9RyREx2E4uNcRnaBr4ydLu3Jz1+ZZOmzEs6wl
    qF94DNBov+Gqij0QRS5l+XKMK2/4UJfVMKSZg8xSxmSTxcTEHWCwRQfdT/hVzds2
    vxgdzqfPjDBeaxr6/GIyADe4cWnhoD+/Oc6x/nuMcF5O7FDKDFq/s1VMrZFQB5vS
    tvxCfSFRG6Qukft1yx+1rZl1JD+uIzbYWv4Q6PicAQKBgQDIYYZVIvpbkji7QotG
    L830ycH5d93pdBWLovkPNa0PVYiGuG4DE1Jqi37YIESgqEXdvT1IJCvx6tfT9OvT
    166OOu7/GxPXAiZeU9K5I9ynp3nJx/JcZSgKhzWvA4kIq0OuA4OjeRwkEONl9uMr
    dLH1cPHYK4VbY6FeKKwLXZTRAQKBgQDB0VWC3ogLQT+7g3sg2sQAmcue/5NGsxk0
    kYPwDshA/9EIaZna90y4XUKd7AUV9uJo1YQHuDioupuay+i516AaVRAsNzVKShiH
    ER0z06EQdQ6ZaZlJ0QCjS3tzJC2gO7lLY/H/Xuzmuz/Y3s2MJxg+gTgyWP6njJsX
    U4ix+oR8hQKBgQCNcnpW4sgDl+ZAGasismAaKcmphfm57929oh9ZozQ0nNYw80OF
    HECTQUEa4zxOhDo9WnZF1HLI5FPSJRPLiHaJpARNRBnvLm9TKqyXUD9UgZ4w19m3
    aximxecZUc+LtQmjbouf+7/nnZxHv82AQXHVphKx25bZeizQwLkhlL+WAQKBgQCh
    xYTXJ8BrjHmSnIqwAIjqa3PucSnPL/vQychTHTN+NUeW+vVlM1bA526L+4y/KYMO
    t3BtNRFtm9v3F01XmKdUcz19elMrf677RYiXUoO0BdA6sk40s5MRuRYAI+lFPbRK
    PdCmMugPKal/7W+pFJSCzz5Fn8xlstFcZefJjez5NQKBgQCMg1pmP0AoPSrLPETM
    4AIfJLTrvcUfC+YaMEQFzRU6gYvreZrQWDlQ7G1gudcUuPG4bbWF3+Ib8GY3z6UL
    R/yF55eAH2hc/yP+Rf02kNO5hA4bqEiy9u9Vpi/jjE0Yb02glSKKiZ2dopuhfJtq
    iSZhCVuSUst50ydQqLAZrgtuDg==
    -----END PRIVATE KEY-----
