apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  postgres.conf: |
    {{- range $key, $val := .Values.postgresql.config }}
    {{ $key }} = {{ $val }}
    {{- end }}
