{{- if .Values.initdb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-init
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
{{- range $name, $content := .Values.initdb.scripts }}
  {{ $name }}: |
{{ $content | indent 4 }}
{{- end }}
{{- end }}
