{{- $root := . -}}
{{- with .Values.certificates }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vernemq.fullname" $root }}-certs
  namespace: {{ include "vernemq.namespace" $root }}
  labels:
    app.kubernetes.io/name: {{ include "vernemq.name" $root }}
    helm.sh/chart: {{ include "vernemq.chart" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
    {{- with .secret }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{ .cert | indent 4 }}
  tls.key: |
{{ .key | indent 4 }}
  ca.crt: |
{{ .ca | indent 4 }}
{{- end }}
